spring:
  datasource:
    url: jdbc:mysql://localhost:3306/merchant_db
    username: root
    password: 123
    driver-class-name:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8080
